# Generated by Django 4.1.1 on 2023-01-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_complain', '0003_alter_flight_flight_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
